#!/usr/bin/env pwsh
# claude-local.ps1 — PowerShell port of the claude-local launcher, so native
# Windows users get `claude --local` without Git Bash (wrapper function in
# shell/claude-wrapper.ps1, installed by shell/install-wrapper.ps1).
#
# Same contract as the bash launcher:
#   claude --local [claude args...]    full-local session straight onto Ollama
#   claude --local --status            reachability + server tuning check
#
# One genuine improvement over bash-on-Windows: server tuning is read from the
# real Windows env scopes (Process, then User/Machine — what the Ollama
# Windows app sees), which the bash launcher cannot do (its launchctl probe is
# macOS-only). Works on any pwsh platform; tests: tests/test-claude-local-ps.ps1.

$OllamaHost = "http://localhost:11434"
$LocalModeDir = Join-Path $HOME '.claude/local-mode'

function Get-ServerSetting([string]$Name) {
    # Session env first, then Windows User/Machine scope (silently $null on
    # non-Windows pwsh, where only the Process scope exists).
    foreach ($scope in 'Process', 'User', 'Machine') {
        $value = [Environment]::GetEnvironmentVariable($Name, $scope)
        if ($value) { return $value }
    }
    return $null
}

function Test-KeepAliveLong([string]$Value) {
    # Mirror of keep_alive_is_long() in the bash launcher — the shared vector
    # file tests/keep-alive-cases.tsv enforces parity between the two.
    if (-not $Value) { return $false }
    if ($Value -match '^-\d') { return $true }   # negative = never unload
    if ($Value -match '^(\d+)h(\d+m?)?$') { return [long]$Matches[1] -ge 1 }
    if ($Value -match '^(\d+)m$') { return [long]$Matches[1] -ge 30 }
    if ($Value -match '^(\d+)s?$') { return [long]$Matches[1] -ge 1800 }
    return $false
}

function Read-ModelsEnv([string]$Path) {
    # models.env is KEY=VALUE lines generated by sync-local.sh.
    $models = @{}
    foreach ($line in Get-Content $Path) {
        if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
        $key, $value = $line -split '=', 2
        $models[$key.Trim()] = $value.Trim()
    }
    return $models
}

function Show-ServerTuningWarnings {
    # Warn-only, like the bash launcher: both settings live server-side.
    $ctx = Get-ServerSetting 'OLLAMA_CONTEXT_LENGTH'
    if (-not ($ctx -match '^\d+$' -and [long]$ctx -ge 65536)) {
        $shown = if ($ctx) { $ctx } else { 'default' }
        Write-Warning ("Ollama server context length looks small or unset ($shown). " +
            "Full-local mode needs >=64K or the session truncates its own instructions. " +
            "Fix: set OLLAMA_CONTEXT_LENGTH=131072 as a Windows env var (System Properties " +
            "-> Environment Variables) or in the Ollama app settings, then restart Ollama. " +
            "(If set in the Ollama app UI, ignore this — it isn't detectable here.)")
    }
    $keepAlive = Get-ServerSetting 'OLLAMA_KEEP_ALIVE'
    if (-not (Test-KeepAliveLong $keepAlive)) {
        $shown = if ($keepAlive) { $keepAlive } else { 'default 5m' }
        Write-Warning ("OLLAMA_KEEP_ALIVE looks short or unset ($shown). " +
            "Idle >5min unloads the orchestrator model; the next turn pays a full " +
            "reload + re-prefill. Set OLLAMA_KEEP_ALIVE=1h (or -1 = never unload) " +
            "the same way, then restart Ollama.")
    }
}

function Resolve-LaunchEnv([hashtable]$Models) {
    # The env Claude Code needs to talk straight to Ollama — must mirror the
    # bash launcher's env block. SMALL_FAST falls back to the main model.
    $smallFast = if ($Models['ANTHROPIC_SMALL_FAST_MODEL']) {
        $Models['ANTHROPIC_SMALL_FAST_MODEL']
    } else { $Models['ANTHROPIC_MODEL'] }
    return @{
        CLAUDE_CONFIG_DIR                        = Join-Path $HOME '.claude-local'
        ANTHROPIC_BASE_URL                       = $OllamaHost
        ANTHROPIC_API_KEY                        = 'ollama-local'
        ANTHROPIC_AUTH_TOKEN                     = 'ollama-local'
        ANTHROPIC_MODEL                          = $Models['ANTHROPIC_MODEL']
        ANTHROPIC_SMALL_FAST_MODEL               = $smallFast
        CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = '1'
    }
}

function Test-OllamaReachable {
    try {
        Invoke-RestMethod -Uri "$OllamaHost/api/tags" -TimeoutSec 3 | Out-Null
        return $true
    } catch { return $false }
}

# Main — guarded so tests can dot-source the functions above without
# launching anything.
if ($MyInvocation.InvocationName -ne '.') {

    if ($args.Count -ge 1 -and $args[0] -in '--status', '-Status') {
        if (Test-OllamaReachable) { Write-Output "Ollama: UP on $OllamaHost" }
        else { Write-Output "Ollama: down" }
        Show-ServerTuningWarnings
        exit 0
    }

    if (-not (Get-Command ollama -ErrorAction SilentlyContinue)) {
        Write-Error ("full-local mode requires Ollama, which is not installed. " +
            "Install it from https://ollama.com/download, then pull models per roles.conf.")
        exit 1
    }
    if (-not (Test-OllamaReachable)) {
        Write-Error "Ollama is installed but not reachable on :11434 — start the Ollama app first."
        exit 1
    }

    Show-ServerTuningWarnings

    $envFile = Join-Path $LocalModeDir 'models.env'
    if (-not (Test-Path $envFile)) {
        # models.env is generated by sync-local.sh (bash). Git Bash provides
        # bash.exe on Windows; without it, point the user there.
        $bash = Get-Command bash -ErrorAction SilentlyContinue
        if (-not $bash) {
            Write-Error ("No models.env yet and no bash found to generate it — " +
                "run sync-local.sh once from Git Bash, then retry.")
            exit 1
        }
        Write-Output "No models.env yet — running sync-local.sh..."
        # Forward slashes: MSYS bash accepts Win32 paths, but not reliably
        # with backslashes as a script argument.
        & $bash.Path ((Join-Path $LocalModeDir 'sync-local.sh') -replace '\\', '/')
        if ($LASTEXITCODE -ne 0 -or -not (Test-Path $envFile)) {
            Write-Error "sync-local.sh failed — fix roles.conf and re-run it from bash."
            exit 1
        }
    }
    $models = Read-ModelsEnv $envFile
    if (-not $models['ANTHROPIC_MODEL']) {
        Write-Error "models.env has no ANTHROPIC_MODEL — re-run sync-local.sh."
        exit 1
    }

    $claude = Get-Command claude -CommandType Application -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if (-not $claude) {
        Write-Error "claude CLI not found on PATH — install Claude Code first."
        exit 1
    }

    # NOTE: run via the wrapper (child shell). Running this script directly in
    # an interactive session leaves these variables set in it afterwards.
    $launchEnv = Resolve-LaunchEnv $models
    foreach ($name in $launchEnv.Keys) {
        [Environment]::SetEnvironmentVariable($name, $launchEnv[$name], 'Process')
    }

    Write-Output "FULL-LOCAL mode — orchestrator: $($env:ANTHROPIC_MODEL) (via Ollama, no proxy)."
    Write-Output "Note: local models are weaker at long agentic chains; keep tasks tight."
    & $claude.Path @args
    exit $LASTEXITCODE
}
