#!/usr/bin/env pwsh
# tests/test-claude-local-ps.ps1 — behavioral tests for the PowerShell port of
# the full-local launcher (claude-local.ps1) and its profile wrapper.
# Keep-alive vectors come from keep-alive-cases.tsv, SHARED with the bash
# test so the two implementations cannot drift.
$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot
$failures = @()

function Check([string]$Name, [bool]$Condition) {
    if ($Condition) { Write-Host "PASS: $Name" }
    else { Write-Host "FAIL: $Name"; $script:failures += $Name }
}

$launcher = Join-Path $repo 'home/claude/local-mode/claude-local.ps1'
$pwshExe = (Get-Process -Id $PID).Path

# --- syntax: every shipped .ps1 must parse cleanly -------------------------
foreach ($rel in @('home/claude/local-mode/claude-local.ps1',
                   'shell/claude-wrapper.ps1',
                   'shell/install-wrapper.ps1')) {
    $path = Join-Path $repo $rel
    if (-not (Test-Path $path)) { Check "syntax: $rel (file exists)" $false; continue }
    $tokens = $null; $parseErrors = $null
    [System.Management.Automation.Language.Parser]::ParseFile(
        $path, [ref]$tokens, [ref]$parseErrors) | Out-Null
    Check "syntax: $rel" ($parseErrors.Count -eq 0)
}

# --- unit: keep-alive check against the shared vector file -----------------
# Dot-sourcing defines the launcher's functions; its main body is guarded
# against dot-source invocation.
. $launcher
$cases = 0
foreach ($line in Get-Content (Join-Path $repo 'tests/keep-alive-cases.tsv')) {
    if ($line -match '^#' -or $line -notmatch "`t") { continue }
    $value, $expected = $line -split "`t", 2
    if ($value -eq '(empty)') { $value = '' }
    $cases++
    $got = if (Test-KeepAliveLong $value) { 'long' } else { 'short' }
    Check "keep-alive: '$value' -> $expected" ($got -eq $expected)
}
Check "keep-alive: shared vector file parsed (>=10 cases)" ($cases -ge 10)

# --- unit: models.env parsing ----------------------------------------------
$tmp = New-TemporaryFile
@'
# AUTO-GENERATED by sync-local.sh — do not edit; edit roles.conf instead.
ANTHROPIC_MODEL=laguna-xs-2.1
ANTHROPIC_SMALL_FAST_MODEL=gemma4:12b
'@ | Set-Content $tmp
$models = Read-ModelsEnv $tmp
Check "models.env: main model parsed" ($models['ANTHROPIC_MODEL'] -eq 'laguna-xs-2.1')
Check "models.env: background model parsed" ($models['ANTHROPIC_SMALL_FAST_MODEL'] -eq 'gemma4:12b')
Check "models.env: exactly the 2 real keys, comments skipped" ($models.Count -eq 2)
Remove-Item $tmp

# --- unit: launch env contract (must mirror the bash launcher's env block) --
$launchEnv = Resolve-LaunchEnv @{ ANTHROPIC_MODEL = 'main-model'
                                  ANTHROPIC_SMALL_FAST_MODEL = 'small-model' }
Check "launch env: main model" ($launchEnv['ANTHROPIC_MODEL'] -eq 'main-model')
Check "launch env: small/fast model" ($launchEnv['ANTHROPIC_SMALL_FAST_MODEL'] -eq 'small-model')
Check "launch env: config dir is ~/.claude-local" `
    ($launchEnv['CLAUDE_CONFIG_DIR'] -eq (Join-Path $HOME '.claude-local'))
Check "launch env: base url points at Ollama" `
    ($launchEnv['ANTHROPIC_BASE_URL'] -eq 'http://localhost:11434')
Check "launch env: nonessential traffic disabled" `
    ($launchEnv['CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC'] -eq '1')
Check "launch env: exactly the bash launcher's 7 variables" ($launchEnv.Count -eq 7)

$fallback = Resolve-LaunchEnv @{ ANTHROPIC_MODEL = 'main-model' }
Check "launch env: SMALL_FAST falls back to the main model" `
    ($fallback['ANTHROPIC_SMALL_FAST_MODEL'] -eq 'main-model')

# --- behavioral: --status runs standalone, exits 0, reports reachability ---
# (child process: the launcher's `exit` must not kill this test run)
$statusOut = & $pwshExe -NoProfile -File $launcher --status 2>$null
Check "--status exits 0 whether Ollama is up or not" ($LASTEXITCODE -eq 0)
Check "--status reports reachability" (($statusOut -join ' ') -match 'Ollama: (UP|down)')

# --- behavioral: the profile wrapper defines a claude function -------------
$wrapper = Join-Path $repo 'shell/claude-wrapper.ps1'
& $pwshExe -NoProfile -Command "
  . '$wrapper'
  if (Get-Command claude -CommandType Function -ErrorAction SilentlyContinue) { exit 0 } else { exit 1 }
"
Check "wrapper defines a 'claude' function when dot-sourced" ($LASTEXITCODE -eq 0)

Write-Host ''
if ($failures.Count) {
    Write-Host "PowerShell launcher tests FAILED ($($failures.Count))."
    exit 1
}
Write-Host "OK — all PowerShell launcher tests passed ($cases keep-alive cases)."
exit 0
